package com.aeroparker.register_form;

import java.time.LocalDateTime;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import jakarta.validation.Valid;

@Controller // This means that this class is a Controller
public class MainController {
    @Autowired // This means to get the bean called CustomerRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CustomerRepository customerRepository;

    @GetMapping("/registeration") // This mapping will automatically run the program starts
    public String homePage(Model model) {
        Iterable<Customer> customers = customerRepository.findAll();
        model.addAttribute("customers", customers);
        return "register-form"; // This will return the register-form.html
    }

    @GetMapping("/success") // This mapping will automatically run the program starts
    public String successPage(Model model) {
        return "success"; // This will return the success.html
    }
    
    public String getMethodName(@RequestParam String param) {
        return new String();
    }
    
    

    @PostMapping(path = "/addCustomer") // Map ONLY POST Requests
    public String addNewCustomer(@RequestParam String first_name, @RequestParam String last_name,
            @RequestParam String email_address, @RequestParam String phone_number,
            @RequestParam String address_line_1, @RequestParam String address_line_2, @RequestParam String city,
            @RequestParam String postcode, @RequestParam String title) {
        // @RequestBody means the returned String is the response, not a view name
        // @ResponseBody means it is a parameter from the GET or POST request

        Customer customer = new Customer();
        customer.setFirstName(first_name);
        customer.setLastName(last_name);
        customer.setEmailAddress(email_address);
        customer.setPhoneNumber(phone_number);
        customer.setAddressLine1(address_line_1);
        customer.setAddressLine2(address_line_2);
        customer.setCity(city);
        customer.setPostcode(postcode);
        customer.setTitle(title);
        customer.setRegistered(LocalDateTime.now());
        
        customerRepository.save(customer);
        return "redirect:/success";
    }

}
